### ISSUE TITLE
Flat button not visible on iPhone 5

### ISSUE THREAD

**Issue by erhiesfeka** [TakeScoop/SwiftyButton#11]
Awesome Library! Thanks. It looks like the Button disappears when launched on an iPhone 5/5s. Is this a bug of some kind? Or am I doing something wrong. Works well on iPhone 6 and greater.

**Comment by erhiesfeka** [comment]
@ldiqual could you let me know if you have any idea about what's going on here?

**Comment by ldiqual** [comment]
@erhiesfeka Can you share a project example, or some code, or a screenshot? Thanks!

**Comment by erhiesfeka** [comment]
@ldiqual Sure! I've attached the zipped project. When you unzip it, you can install the 'SwiftyButton' pod if you haven't already and run the project on the iPhone simulator. You will notice that the green button is NOT visible or clickable on the iphone 5 Simulator, but it is visible and clickable on the iPhone 6 simulator. I've tested on real devices as well and got the same results. Thanks!!
[SwiftyButtom.zip](https://github.com/TakeScoop/SwiftyButton/files/1173296/SwiftyButtom.zip)

**Comment by ldiqual** [comment]
@erhiesfeka This is because of your button vertical constraints which compress its height down to 0.

![image](https://user-images.githubusercontent.com/941453/28598885-7c682766-715b-11e7-91cf-ab19987a3778.png)

Try to change the constraints so that the button aligns vertically instead:

![image](https://user-images.githubusercontent.com/941453/28598882-76ae8220-715b-11e7-80f6-79dae9535bad.png)

**Comment by erhiesfeka** [comment]
@ldiqual Thanks a lot. That was the issue exactly. I'll go ahead and close the issue.
